name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  custom_test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    name: Generate Release
    steps:
      - name: checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Generate Changelog
        uses: ./
        id: changelog
        with:
          next_tag: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1.18.0
        with:
          makeLatest: true
          token: ${{ github.token }}
          body: ${{ steps.changelog.outputs.changelog }}
          name: "Release ${{ github.ref_name }}"

      - name: Create additional Major/Minor tags
        uses: vweevers/additional-tags-action@3bab55b44e81186dcfef7db9f2cbca01a78eb710 # v2
