name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  custom_test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: read

    name: Generate Release
    steps:
      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Generate Changelog
        uses: ./
        id: changelog
        with:
          next_tag: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # v1.13.0
        with:
          makeLatest: true
          token: ${{ github.token }}
          body: ${{ steps.changelog.outputs.changelog }}
          name: "Release ${{ github.ref_name }}"

      - name: Create additional Major/Minor tags
        uses: vweevers/additional-tags-action@3bab55b44e81186dcfef7db9f2cbca01a78eb710 # v2
